version: '3.4'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'aord'
      MYSQL_ROOT_PASSWORD: 'rootroot'
    ports:
      - '3307:3306'
    volumes:
      - mysql-db:/var/lib/mysql

  aord-backend:
    build: ./Aut_of_risk_determination_BE
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/aord?allowPublicKeyRetrieval=true&useSSL=false
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql-db: