version: '3.4'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'aord'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql

  aord-backend:
    build: ./Aut_of_risk_determination_BE
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/aord?allowPublicKeyRetrieval=true&useSSL=false
    ports:
      - "8080:8080"
    depends_on:
      - db

  aord-frontend:
    build: ./Aut_of_risk_determination_FE/aut_of_risk_determination
    ports:
      - "4200:80"
    depends_on:
      - aord-backend

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: aord-mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

volumes:
  mysql-db: