version: '3'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=aord
      - MYSQL_ROOT_PASSWORD=root

  backend:
    restart: always
    build:
      context: ./Aut_of_risk_determination_BE
      dockerfile: Dockerfile.dev
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/aord?allowPublicKeyRetrieval=true&useSSL=false
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: 
      context: ./Aut_of_risk_determination_FE/aut_of_risk_determination
      dockerfile: Dockerfile.dev
    ports:
      - "4200:80"
    depends_on:
      - backend