FROM maven:3.5.2-jdk-8-alpine

FROM alpine:3.10

RUN apk --no-cache add openjdk11 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
RUN apk add bash vim curl wget jq docker git tar unzip bash-completion ca-certificates
RUN cd /opt && curl -sSl http://mirror.vorboss.net/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz | tar -xz

ENV PATH "$PATH:/opt/apache-maven-3.6.3/bin"
ENV DB_ADDRESS host.docker.internal
ENV PORT 8080

WORKDIR '/app'

COPY . .

EXPOSE $PORT

CMD mvn spring-boot:run